### ISSUE TITLE
询问前项目tools-vue中背景模版设置

### ISSUE THREAD

**Issue by beyondliaaaa** [kooriookami/yugioh-card-pic#1]
您好，您之前的项目tools-vue我们很喜欢，一直在本地使用。现在您似乎将其指向的卡模移除了，贴吧原作者白羽幸鳥似乎也已经将其链接移除。请问能否麻烦分享一套卡模？谢谢。

**Comment by kooriookami** [comment]
白羽幸鳥在贴吧分享了卡模
https://tieba.baidu.com/p/7904373562
https://pan.baidu.com/s/11bF68eli9ELaNJVpinxQzA?pwd=jpyt

**Comment by beyondliaaaa** [comment]
感谢，是我的疏忽没找到新链接。
方便的话能否再指教一下如何修改您之前的项目使其指向本地卡模文件？麻烦您了。

**Comment by kooriookami** [comment]
这个不行了，服务器重置了，图片只能自己从模板里自己截取了。

**Comment by beyondliaaaa** [comment]
好的，谢谢回复，祝安好
